import logging

from sqlalchemy.orm import Session

from app.config import settings
from app.models import AdminUser, Artisan, SiteVitrine
from app.security import hash_password

logger = logging.getLogger("suite_artisan.admin")

# Historical content generated by the removed site-generation engines. It
# remains stored for auditability, but is omitted from the Site Vitrine
# content shown/edited in Admin because it was not supplied by the artisan
# and includes unsupported claims in some trades.
LEGACY_GENERATED_CONTENT = (
    ("Votre plombier de confiance, intervention rapide", ["Dépannage fuite d'eau", "Installation sanitaire", "Chauffe-eau & chaudière", "Débouchage de canalisation", "Rénovation de salle de bain"]),
    ("Électricien certifié, intervention rapide et aux normes", ["Mise aux normes électriques", "Installation de tableau électrique", "Dépannage électrique urgent", "Domotique & éclairage connecté", "Prises, interrupteurs & éclairage"]),
    ("Maçonnerie et gros œuvre : du solide, du durable", ["Fondations & gros œuvre", "Extension de maison", "Rénovation de façade", "Dalle béton & terrasse", "Ouverture de mur porteur"]),
    ("Peinture intérieure & extérieure, un rendu impeccable", ["Peinture intérieure", "Peinture de façade extérieure", "Pose de papier peint", "Enduits décoratifs", "Ravalement de façade"]),
    ("Agencements et ouvrages en bois conçus avec précision", ["Agencement intérieur sur mesure", "Mobilier et rangements intégrés", "Portes, fenêtres et menuiseries", "Escaliers et ouvrages en bois", "Rénovation de menuiseries"]),
    ("Transformer les espaces avec une vision d’ensemble", ["Rénovation complète d’intérieur", "Réaménagement des volumes", "Rénovation de cuisine et salle de bain", "Coordination des corps de métier", "Finitions et mise en valeur"]),
    ("Artisan du BTP : qualité, sérieux et devis gratuit", ["Travaux de rénovation", "Petits travaux du quotidien", "Entretien du bâtiment", "Devis gratuit sous 48h"]),
)


def _has_legacy_generated_content(stored: dict) -> bool:
    return any(stored.get("tagline") == tagline and stored.get("services") == services for tagline, services in LEGACY_GENERATED_CONTENT)


def ensure_bootstrap_admin(db: Session) -> None:
    """Cree le premier compte admin depuis l'environnement, une seule fois."""
    if not settings.admin_email and not settings.admin_password:
        return
    if not settings.admin_email or not settings.admin_password:
        logger.error("ADMIN_EMAIL et ADMIN_PASSWORD doivent etre definis ensemble")
        return
    if len(settings.admin_password) < 12:
        raise RuntimeError("ADMIN_PASSWORD doit contenir au moins 12 caracteres")
    email = settings.admin_email.strip().lower()
    if db.query(AdminUser).filter(AdminUser.email == email).first() is not None:
        return
    db.add(AdminUser(email=email, password_hash=hash_password(settings.admin_password), nom=settings.admin_name, actif=True))
    db.commit()
    logger.info("Compte Admin Suite Artisan initialise pour %s", email)


def default_site_config(artisan: Artisan) -> dict:
    return {
        "tagline": "",
        "services": [],
        "stats": [],
    }


def merged_site_config(artisan: Artisan, site: SiteVitrine | None) -> dict:
    config = default_site_config(artisan)
    if site and site.config:
        stored = dict(site.config)
        if _has_legacy_generated_content(stored):
            stored.pop("tagline", None)
            stored.pop("services", None)
        config.update(stored)
    return config


def site_content_warnings(artisan: Artisan, site: SiteVitrine | None) -> list[str]:
    if not site or not site.config:
        return []
    stored = dict(site.config)
    return ["Les anciens textes générés ont été écartés du rendu. Renseignez uniquement le contenu confirmé par l’artisan."] if _has_legacy_generated_content(stored) else []
