import html
import logging
import sys
from pathlib import Path

from sqlalchemy.orm import Session

from app.config import settings
from app.design_schemas import validate_design_profile
from app.models import AdminUser, Artisan, Avis, SiteVitrine, utcnow
from app.security import hash_password
from app.site_media_selection_service import ensure_media_profile, media_overview_dict, media_profile_dict
from app.storage import get_storage

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from generator.site_generator import generate_site  # noqa: E402
from generator.v3.grammar import AMBIENCES, ART_DIRECTIONS, CONTENT_DENSITIES, PAGE_SILHOUETTES, PROFILE_VALUES as V3_PROFILE_VALUES  # noqa: E402
from generator.v3.selector import (  # noqa: E402
    build_design_signature as build_v3_signature,
    select_design_grammar,
    similarity_score as v3_similarity_score,
)

logger = logging.getLogger("suite_artisan.admin")

# Historical content generated by the removed engines. It remains stored for
# auditability, but is omitted from V3 output because it was not supplied by
# the artisan and includes unsupported claims in some trades.
LEGACY_GENERATED_CONTENT = (
    ("Votre plombier de confiance, intervention rapide", ["Dépannage fuite d'eau", "Installation sanitaire", "Chauffe-eau & chaudière", "Débouchage de canalisation", "Rénovation de salle de bain"]),
    ("Électricien certifié, intervention rapide et aux normes", ["Mise aux normes électriques", "Installation de tableau électrique", "Dépannage électrique urgent", "Domotique & éclairage connecté", "Prises, interrupteurs & éclairage"]),
    ("Maçonnerie et gros œuvre : du solide, du durable", ["Fondations & gros œuvre", "Extension de maison", "Rénovation de façade", "Dalle béton & terrasse", "Ouverture de mur porteur"]),
    ("Peinture intérieure & extérieure, un rendu impeccable", ["Peinture intérieure", "Peinture de façade extérieure", "Pose de papier peint", "Enduits décoratifs", "Ravalement de façade"]),
    ("Agencements et ouvrages en bois conçus avec précision", ["Agencement intérieur sur mesure", "Mobilier et rangements intégrés", "Portes, fenêtres et menuiseries", "Escaliers et ouvrages en bois", "Rénovation de menuiseries"]),
    ("Transformer les espaces avec une vision d’ensemble", ["Rénovation complète d’intérieur", "Réaménagement des volumes", "Rénovation de cuisine et salle de bain", "Coordination des corps de métier", "Finitions et mise en valeur"]),
    ("Artisan du BTP : qualité, sérieux et devis gratuit", ["Travaux de rénovation", "Petits travaux du quotidien", "Entretien du bâtiment", "Devis gratuit sous 48h"]),
)


def _has_legacy_generated_content(stored: dict) -> bool:
    return any(stored.get("tagline") == tagline and stored.get("services") == services for tagline, services in LEGACY_GENERATED_CONTENT)


def ensure_bootstrap_admin(db: Session) -> None:
    """Cree le premier compte admin depuis l'environnement, une seule fois."""
    if not settings.admin_email and not settings.admin_password:
        return
    if not settings.admin_email or not settings.admin_password:
        logger.error("ADMIN_EMAIL et ADMIN_PASSWORD doivent etre definis ensemble")
        return
    if len(settings.admin_password) < 12:
        raise RuntimeError("ADMIN_PASSWORD doit contenir au moins 12 caracteres")
    email = settings.admin_email.strip().lower()
    if db.query(AdminUser).filter(AdminUser.email == email).first() is not None:
        return
    db.add(AdminUser(email=email, password_hash=hash_password(settings.admin_password), nom=settings.admin_name, actif=True))
    db.commit()
    logger.info("Compte Admin Suite Artisan initialise pour %s", email)


def default_site_config(artisan: Artisan) -> dict:
    return {
        "tagline": "",
        "services": [],
        "stats": [],
    }


def merged_site_config(artisan: Artisan, site: SiteVitrine | None) -> dict:
    config = default_site_config(artisan)
    if site and site.config:
        stored = dict(site.config)
        if _has_legacy_generated_content(stored):
            stored.pop("tagline", None)
            stored.pop("services", None)
        config.update(stored)
    return config


def site_content_warnings(artisan: Artisan, site: SiteVitrine | None) -> list[str]:
    if not site or not site.config:
        return []
    stored = dict(site.config)
    return ["Les anciens textes générés ont été écartés du rendu V3. Renseignez uniquement le contenu confirmé par l’artisan."] if _has_legacy_generated_content(stored) else []


def _design_profile_artisan_payload(artisan: Artisan) -> dict:
    """Minimal real-data context used by the deterministic V3 selector."""
    return {"slug": artisan.slug, "siret": artisan.siret, "nom_entreprise": artisan.nom_entreprise, "metier": artisan.metier}


def _valid_stored_profile(site: SiteVitrine) -> dict | None:
    """Return a valid V3 profile; historical V2 data is never executable."""
    if not site.design_profile:
        return None
    try:
        return validate_design_profile(site.design_profile)
    except Exception:
        logger.warning("design_profile non V3 ou invalide pour le site %s", site.id)
        return None


def is_historical_v2_profile(profile: object) -> bool:
    return isinstance(profile, dict) and str(profile.get("design_engine_version") or "").startswith("v2")


def _autres_profils(db: Session, site: SiteVitrine) -> list[dict]:
    """Recent profiles from other sites, used by V3 anti-cloning."""
    return [
        profil for (profil,) in db.query(SiteVitrine.design_profile).filter(
            SiteVitrine.id != (site.id or -1), SiteVitrine.design_profile.isnot(None),
        ).order_by(SiteVitrine.id.desc()).limit(50).all()
        if profil
    ]


def ensure_design_profile(db: Session, artisan: Artisan, site: SiteVitrine) -> dict:
    """Create a stable V3 profile only for a site that has no design yet."""
    existing = _valid_stored_profile(site)
    if existing is not None:
        return existing
    if site.design_profile:
        if is_historical_v2_profile(site.design_profile):
            raise ValueError(
                "Ancien design detecte : generez une alternative V3, previsualisez-la puis adoptez-la."
            )
        raise ValueError("Le design enregistre est invalide; une regeneration V3 explicite est requise.")

    preferences = site.design_preferences or {}
    profile, _distinct = select_design_grammar(
        _design_profile_artisan_payload(artisan),
        _autres_profils(db, site),
        direction=preferences.get("preferred_direction"),
        ambience=preferences.get("ambience"),
        density=preferences.get("density"),
    )
    profile = validate_design_profile(profile)

    site.design_profile = profile
    db.commit()
    db.refresh(site)
    return profile


# ---------- Configurateur Admin (Lot 4) : preferences, candidate, adopt/abandon ----------

DENSITY_VALUES = set(CONTENT_DENSITIES)
CANDIDATE_OVERRIDE_FIELDS = set(V3_PROFILE_VALUES)


def validate_design_preferences(payload: dict) -> dict:
    """Valide des preferences Admin (Niveau 1) contre le registre - jamais de
    confiance aveugle envers le frontend (voir le brief, section 33)."""
    density = payload.get("density")
    if density is not None and density not in DENSITY_VALUES:
        raise ValueError(f"density doit etre l'une de : {sorted(DENSITY_VALUES)}")
    preferred_direction = payload.get("preferred_direction")
    if preferred_direction is not None and preferred_direction not in ART_DIRECTIONS:
        raise ValueError(f"preferred_direction doit etre l'une de : {sorted(ART_DIRECTIONS)}")
    ambience = payload.get("ambience")
    if ambience is not None and ambience not in AMBIENCES:
        raise ValueError(f"ambience doit etre l'une de : {sorted(AMBIENCES)}")
    result = {"density": density}
    if preferred_direction is not None:
        result["preferred_direction"] = preferred_direction
    if ambience is not None:
        result["ambience"] = ambience
    return result


def _apply_candidate_overrides(candidate: dict, overrides: dict | None) -> dict:
    """Applique des reglages avances (Niveau 2) sur une candidate deja
    generee par le moteur, puis revalide integralement le resultat contre
    le schema V3 (jamais confiance en une valeur venue du frontend) et
    recalcule design_signature en consequence - une candidate avec overrides
    reste donc toujours un design_profile valide et coherent."""
    if not overrides:
        return candidate
    inconnues = set(overrides) - CANDIDATE_OVERRIDE_FIELDS
    if inconnues:
        raise ValueError(f"Reglages avances inconnus : {sorted(inconnues)}")
    merged = {**candidate, **overrides}
    merged["design_signature"] = "temp"
    merged = validate_design_profile(merged)
    merged["design_signature"] = build_v3_signature(merged)
    return merged


def candidate_preview_storage_key(artisan_id: int) -> str:
    if artisan_id <= 0:
        raise ValueError("Identifiant artisan invalide")
    return f"admin-site-previews/{artisan_id}/candidate.html"


def generate_design_candidate(
    db: Session,
    artisan: Artisan,
    site: SiteVitrine,
    *,
    density: str | None = None,
    overrides: dict | None = None,
    avoid_previous_candidate: bool = False,
    preferred_direction: str | None = None,
    ambience: str | None = None,
) -> tuple[dict, bool]:
    """Genere (ou remplace) l'alternative de design d'un site - NE TOUCHE
    JAMAIS a site.design_profile (le "current" reste stable tant que
    l'Admin n'a pas explicitement adopte, voir adopt_design_candidate).

    Retourne (candidate, distinct) : distinct=False si aucune tentative
    n'etait suffisamment differente du current (reponse honnete, voir le
    brief - jamais un echec silencieux ni une fausse distinction)."""
    current_raw = site.design_profile
    current_v3 = _valid_stored_profile(site)
    if current_raw is None:
        raise ValueError("Le site doit avoir un design actuel avant de generer une alternative")
    if current_v3 is None and not is_historical_v2_profile(current_raw):
        raise ValueError("Le design actuel est invalide et ne peut pas servir au workflow V3")

    exclude = set()
    if current_v3:
        exclude.add(current_v3.get("design_signature") or "")
    if avoid_previous_candidate:
        previous = _valid_stored_profile_field(site, "candidate_design_profile")
        if previous is not None:
            exclude.add(previous.get("design_signature") or "")

    candidate, distinct = select_design_grammar(
        _design_profile_artisan_payload(artisan), _autres_profils(db, site),
        direction=preferred_direction, ambience=ambience, density=density,
        exclude_signatures=exclude,
    )
    candidate = validate_design_profile(candidate)
    candidate = _apply_candidate_overrides(candidate, overrides)
    if overrides:
        # Un override explicite peut legitimement rapprocher la candidate du
        # current (l'Admin sait ce qu'il fait en reglages avances) : on
        # rapporte honnetement la distance reelle plutot que de la masquer.
        distinct = current_v3 is None or v3_similarity_score(candidate, current_v3) < .58

    site.candidate_design_profile = candidate
    db.commit()
    db.refresh(site)
    generate_candidate_preview(db, artisan, site)
    return candidate, distinct


def _valid_stored_profile_field(site: SiteVitrine, field: str) -> dict | None:
    value = getattr(site, field, None)
    if not value:
        return None
    try:
        return validate_design_profile(value)
    except Exception:
        return None


def abandon_design_candidate(db: Session, artisan: Artisan, site: SiteVitrine) -> None:
    """Supprime l'alternative en cours sans jamais toucher au current ni au
    site publie (voir le brief, section 19)."""
    site.candidate_design_profile = None
    db.commit()
    storage_key = candidate_preview_storage_key(artisan.id)
    storage = get_storage()
    if storage.exists(storage_key):
        storage.delete(storage_key)


def adopt_design_candidate(db: Session, artisan: Artisan, site: SiteVitrine) -> dict:
    """Le candidate devient le nouveau current - seule action de ce lot qui
    modifie design_profile. Ne publie JAMAIS automatiquement : la
    regeneration qui suit (generate_site_preview) remet le site a l'etat
    "genere", exactement comme n'importe quel autre changement de
    configuration suivi d'une regeneration (voir admin_site_update) - un
    site "pret" ou "publie" doit donc explicitement repasser par "pret" puis
    "publie" apres adoption (voir le brief, sections 17-18)."""
    candidate = _valid_stored_profile_field(site, "candidate_design_profile")
    if candidate is None:
        raise ValueError("Aucune alternative a adopter")
    site.design_profile = candidate
    site.candidate_design_profile = None
    db.commit()
    db.refresh(site)
    abandon_design_candidate(db, artisan, site)  # nettoie le fichier de preview candidate devenu obsolete
    generate_site_preview(db, artisan, site)
    return candidate


def generate_candidate_preview(db: Session, artisan: Artisan, site: SiteVitrine) -> str:
    """Rendu HTML de l'alternative, isole du current : n'ecrit jamais dans
    site.design_profile ni site.storage_key (voir le brief, section 14).
    Reutilise le meme pipeline de rendu (generate_site) et la meme API de
    preview isolee (/admin/preview-api) que la preview courante."""
    candidate = _valid_stored_profile_field(site, "candidate_design_profile")
    if candidate is None:
        raise ValueError("Aucune alternative a previsualiser")
    ensure_media_profile(db, artisan, site)
    config = merged_site_config(artisan, site)
    payload = build_generator_payload(db, artisan, config, site)
    payload["design_profile"] = candidate
    generated_html = generate_site(payload, api_base_url="/admin/preview-api")
    get_storage().save(candidate_preview_storage_key(artisan.id), generated_html.encode("utf-8"))
    return generated_html


def sections_availability(db: Session, artisan: Artisan, site: SiteVitrine) -> list[dict]:
    """Describe V3 sections using only facts and media actually available."""
    config = merged_site_config(artisan, site)
    media = media_profile_dict(db, artisan, site, admin=True)
    disponible = {
        "assurance_decennale_nom": bool(artisan.assurance_decennale_nom),
        "services": bool(config.get("services")),
        "photos": media.get("has_gallery", False),
        "avis": db.query(Avis).filter(Avis.artisan_id == artisan.id, Avis.publie_site.is_(True)).count() > 0,
        "ville": bool(artisan.ville),
        "stats": bool(config.get("stats")),
        "photos_avant_apres": media.get("has_before_after", False),
    }
    labels = {
        "hero": "Hero", "trust": "Assurance décennale", "services": "Prestations",
        "featured_project": "Réalisation en avant", "about": "À propos",
        "gallery": "Galerie photo", "reviews": "Avis clients", "service_area": "Zone d'intervention",
        "cta": "Appel à l'action", "stats": "Chiffres clés", "process": "Étapes",
        "before_after": "Avant / après", "reasons": "Nos engagements", "contact": "Formulaire de contact",
    }
    requirements = {
        "hero": [], "manifesto": [], "services": ["services"], "gallery": ["photos"],
        "featured_project": ["photos"], "about": ["ville"], "process": ["process_steps"],
        "before_after": ["photos_avant_apres"], "trust": ["assurance_decennale_nom"],
        "stats": ["stats"], "reviews": ["avis"], "service_area": ["ville"], "contact": [],
    }
    disponible["process_steps"] = False
    sections = dict.fromkeys(section for order in PAGE_SILHOUETTES.values() for section in order)
    result = []
    for section in sections:
        requires = requirements.get(section, [])
        ok = all(disponible.get(key) for key in requires)
        raison = None if ok else "Cette section n'apparaît pas car aucune donnée n'est disponible."
        result.append({"section": section, "label": labels.get(section, section), "disponible": ok, "raison": raison})
    return result


def preview_storage_key(artisan_id: int) -> str:
    if artisan_id <= 0:
        raise ValueError("Identifiant artisan invalide")
    return f"admin-site-previews/{artisan_id}/index.html"


def _safe_text(value: str | None) -> str:
    return html.escape(value or "", quote=True)


def build_generator_payload(
    db: Session,
    artisan: Artisan,
    config: dict,
    site: SiteVitrine | None = None,
) -> dict:
    avis = db.query(Avis).filter(Avis.artisan_id == artisan.id, Avis.publie_site.is_(True)).all()
    media_overview = media_overview_dict(db, artisan, admin=True)
    media_profile = media_overview["profile"]
    return {
        "_content_escaped": True,
        "nom_entreprise": _safe_text(artisan.nom_entreprise),
        "metier": artisan.metier,
        "slug": artisan.slug,
        "ville": _safe_text(artisan.ville),
        "code_postal": _safe_text(artisan.code_postal),
        "telephone": _safe_text(artisan.telephone),
        "email": _safe_text(artisan.email),
        "adresse": _safe_text(artisan.adresse),
        "siret": _safe_text(artisan.siret),
        "assurance_decennale_nom": _safe_text(artisan.assurance_decennale_nom),
        "tagline": _safe_text(config.get("tagline")),
        "services": [_safe_text(item) for item in config.get("services") or []],
        "stats": [
            {"valeur": _safe_text(item.get("valeur")), "label": _safe_text(item.get("label"))}
            for item in config.get("stats") or []
        ],
        "avis": [
            {"note": item.note, "commentaire": _safe_text(item.commentaire), "nom_auteur": _safe_text(item.nom_auteur)}
            for item in avis
        ],
        "has_logo": media_profile["has_logo"],
        "artisan_photo_count": media_profile["artisan_photo_count"],
        "has_gallery": media_profile["has_gallery"],
        "has_before_after": media_profile["has_before_after"],
        "selected_media": media_profile["selections"],
        "logo": media_overview["logo"],
        "design_profile": dict(site.design_profile) if site and site.design_profile else None,
        "url_publique": _safe_text(site.url_publique) if site else "",
    }


def generate_site_preview(db: Session, artisan: Artisan, site: SiteVitrine) -> str:
    # A missing profile is selected once in V3. Historical V2 profiles are
    # deliberately rejected here and migrate only through candidate/adoption.
    ensure_design_profile(db, artisan, site)
    ensure_media_profile(db, artisan, site)
    config = merged_site_config(artisan, site)
    payload = build_generator_payload(db, artisan, config, site)
    generated_html = generate_site(payload, api_base_url="/admin/preview-api")
    storage_key = preview_storage_key(artisan.id)
    get_storage().save(storage_key, generated_html.encode("utf-8"))
    site.storage_key = storage_key
    site.statut = "genere"
    site.date_generation = utcnow()
    artisan.site_statut = "en_cours"
    db.commit()
    db.refresh(site)
    return generated_html
