"""archivage clients devis factures chantiers

Revision ID: 42665248ff48
Revises: d9d87b93c80b
Create Date: 2026-08-26 00:47:10.904473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42665248ff48'
down_revision: Union[str, None] = 'd9d87b93c80b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chantiers', sa.Column('archive', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('clients', sa.Column('archive', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('devis', sa.Column('archive', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('factures', sa.Column('archive', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('factures', 'archive')
    op.drop_column('devis', 'archive')
    op.drop_column('clients', 'archive')
    op.drop_column('chantiers', 'archive')
    # ### end Alembic commands ###
