"""sequence numero devis factures

Revision ID: 42d3e0b23a14
Revises: d3b7496d76a8
Create Date: 2026-08-26 03:44:29.170284

"""
import re
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42d3e0b23a14'
down_revision: Union[str, None] = 'd3b7496d76a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Reconnait DEV-2026-0001 / FAC-2026-0001 (l'ancien schema de numerotation,
# genere par un simple count()+1 avant cette migration).
_NUMERO_RE = re.compile(r"^[A-Za-z]+-(\d{4})-(\d+)$")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('numero_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artisan_id', sa.Integer(), nullable=False),
    sa.Column('type_document', sa.String(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('dernier_numero', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artisan_id', 'type_document', 'annee', name='uq_numero_sequence_artisan_type_annee')
    )
    op.create_index(op.f('ix_numero_sequences_artisan_id'), 'numero_sequences', ['artisan_id'], unique=False)
    op.create_index(op.f('ix_numero_sequences_id'), 'numero_sequences', ['id'], unique=False)
    # ### end Alembic commands ###

    # Retropeuplement : sans ca, la premiere creation de devis/facture apres
    # cette migration repartirait a 0001 pour l'annee en cours et entrerait
    # en collision avec un numero deja emis (l'ancien schema comptait
    # simplement les lignes, sans jamais persister de compteur). On derive
    # le compteur de depart du plus grand numero deja emis par artisan/annee,
    # pas d'un count() qui sous-estimerait en cas de document archive/supprime.
    connexion = op.get_bind()
    numero_sequences = sa.table(
        "numero_sequences",
        sa.column("artisan_id", sa.Integer),
        sa.column("type_document", sa.String),
        sa.column("annee", sa.Integer),
        sa.column("dernier_numero", sa.Integer),
    )
    for type_document, nom_table in (("devis", "devis"), ("facture", "factures")):
        lignes = connexion.execute(
            sa.text(f"SELECT artisan_id, numero FROM {nom_table} WHERE numero IS NOT NULL")
        ).fetchall()
        dernier_par_cle: dict[tuple[int, int], int] = {}
        for artisan_id, numero in lignes:
            correspondance = _NUMERO_RE.match(numero or "")
            if not correspondance:
                continue
            annee, valeur = int(correspondance.group(1)), int(correspondance.group(2))
            cle = (artisan_id, annee)
            dernier_par_cle[cle] = max(dernier_par_cle.get(cle, 0), valeur)
        for (artisan_id, annee), dernier_numero in dernier_par_cle.items():
            connexion.execute(
                numero_sequences.insert().values(
                    artisan_id=artisan_id, type_document=type_document, annee=annee, dernier_numero=dernier_numero,
                )
            )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_numero_sequences_id'), table_name='numero_sequences')
    op.drop_index(op.f('ix_numero_sequences_artisan_id'), table_name='numero_sequences')
    op.drop_table('numero_sequences')
    # ### end Alembic commands ###
