"""baseline schema V3

Revision ID: 7e066477f1a8
Revises: 
Create Date: 2026-08-25 23:58:51.591660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e066477f1a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artisans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('nom_entreprise', sa.String(), nullable=False),
    sa.Column('metier', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('ville', sa.String(), nullable=True),
    sa.Column('code_postal', sa.String(), nullable=True),
    sa.Column('adresse', sa.String(), nullable=True),
    sa.Column('siret', sa.String(), nullable=True),
    sa.Column('assurance_decennale_nom', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('site_url', sa.String(), nullable=True),
    sa.Column('site_statut', sa.String(), nullable=True),
    sa.Column('onboarding_termine', sa.Boolean(), nullable=True),
    sa.Column('relance_devis_j1', sa.Integer(), nullable=True),
    sa.Column('relance_devis_j2', sa.Integer(), nullable=True),
    sa.Column('relance_devis_j3', sa.Integer(), nullable=True),
    sa.Column('relance_facture_jours', sa.Integer(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('subscription_status', sa.String(), nullable=True),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artisans_email'), 'artisans', ['email'], unique=True)
    op.create_index(op.f('ix_artisans_id'), 'artisans', ['id'], unique=False)
    op.create_index(op.f('ix_artisans_slug'), 'artisans', ['slug'], unique=True)
    op.create_table('automation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nb_devis_relances', sa.Integer(), nullable=True),
    sa.Column('nb_factures_relancees', sa.Integer(), nullable=True),
    sa.Column('nb_alertes_conformite', sa.Integer(), nullable=True),
    sa.Column('nb_emails_envoyes', sa.Integer(), nullable=True),
    sa.Column('nb_emails_non_configures', sa.Integer(), nullable=True),
    sa.Column('nb_erreurs', sa.Integer(), nullable=True),
    sa.Column('erreur', sa.Text(), nullable=True),
    sa.Column('nb_contrats_factures', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_runs_id'), 'automation_runs', ['id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artisan_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('societe', sa.String(), nullable=True),
    sa.Column('adresse', sa.String(), nullable=True),
    sa.Column('code_postal', sa.String(), nullable=True),
    sa.Column('ville', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('montant_estime', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('probabilite', sa.Integer(), nullable=True),
    sa.Column('prochaine_action', sa.String(), nullable=True),
    sa.Column('token_avis', sa.String(), nullable=True),
    sa.Column('token_portail', sa.String(), nullable=True),
    sa.Column('token_portail_genere_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_artisan_id'), 'clients', ['artisan_id'], unique=False)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_statut'), 'clients', ['statut'], unique=False)
    op.create_index(op.f('ix_clients_token_avis'), 'clients', ['token_avis'], unique=True)
    op.create_index(op.f('ix_clients_token_portail'), 'clients', ['token_portail'], unique=True)
    op.create_table('conformite_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artisan_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('libelle', sa.String(), nullable=False),
    sa.Column('date_expiration', sa.Date(), nullable=False),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conformite_items_artisan_id'), 'conformite_items', ['artisan_id'], unique=False)
    op.create_index(op.f('ix_conformite_items_id'), 'conformite_items', ['id'], unique=False)
    op.create_table('fournisseurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artisan_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('categorie', sa.String(), nullable=True),
    sa.Column('contact_nom', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('adresse', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fournisseurs_artisan_id'), 'fournisseurs', ['artisan_id'], unique=False)
    op.create_index(op.f('ix_fournisseurs_id'), 'fournisseurs', ['id'], unique=False)
    op.create_table('membres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artisan_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membres_artisan_id'), 'membres', ['artisan_id'], unique=False)
    op.create_index(op.f('ix_membres_email'), 'membres', ['email'], unique=True)
    op.create_index(op.f('ix_membres_id'), 'membres', ['id'], unique=False)
    op.create_table('prestations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artisan_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('categorie', sa.String(), nullable=True),
    sa.Column('unite', sa.String(), nullable=True),
    sa.Column('prix_unitaire_ht', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('taux_tva', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prestations_artisan_id'), 'prestations', ['artisan_id'], unique=False)
    op.create_index(op.f('ix_prestations_id'), 'prestations', ['id'], unique=False)
    op.create_table('avis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artisan_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Integer(), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('nom_auteur', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('publie_site', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisans.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avis_artisan_id'), 'avis', ['artisan_id'], unique=False)
    op.create_index(op.f('ix_avis_client_id'), 'avis', ['client_id'], unique=False)
    op.create_index(op.f('ix_avis_id'), 'avis', ['id'], unique=False)
    op.create_table('contrats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artisan_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('montant_ht', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('taux_tva', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('frequence', sa.String(), nullable=False),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('prochaine_echeance', sa.Date(), nullable=False),
    sa.Column('derniere_generation', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisans.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contrats_artisan_id'), 'contrats', ['artisan_id'], unique=False)
    op.create_index(op.f('ix_contrats_client_id'), 'contrats', ['client_id'], unique=False)
    op.create_index(op.f('ix_contrats_id'), 'contrats', ['id'], unique=False)
    op.create_table('devis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artisan_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('titre', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('taux_tva', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('acompte_pourcentage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('remise_pourcentage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('date_envoi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_consultation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_derniere_relance', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nb_relances', sa.Integer(), nullable=True),
    sa.Column('date_signature', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nom_signataire', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisans.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devis_artisan_id'), 'devis', ['artisan_id'], unique=False)
    op.create_index(op.f('ix_devis_client_id'), 'devis', ['client_id'], unique=False)
    op.create_index(op.f('ix_devis_id'), 'devis', ['id'], unique=False)
    op.create_index(op.f('ix_devis_statut'), 'devis', ['statut'], unique=False)
    op.create_index(op.f('ix_devis_token'), 'devis', ['token'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artisan_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('expediteur', sa.String(), nullable=False),
    sa.Column('texte', sa.Text(), nullable=False),
    sa.Column('lu', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisans.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_artisan_id'), 'messages', ['artisan_id'], unique=False)
    op.create_index(op.f('ix_messages_client_id'), 'messages', ['client_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('chantiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artisan_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('devis_id', sa.Integer(), nullable=True),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('adresse', sa.String(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin_prevue', sa.Date(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('date_reception', sa.Date(), nullable=True),
    sa.Column('reserves', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisans.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['devis_id'], ['devis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chantiers_artisan_id'), 'chantiers', ['artisan_id'], unique=False)
    op.create_index(op.f('ix_chantiers_client_id'), 'chantiers', ['client_id'], unique=False)
    op.create_index(op.f('ix_chantiers_devis_id'), 'chantiers', ['devis_id'], unique=False)
    op.create_index(op.f('ix_chantiers_id'), 'chantiers', ['id'], unique=False)
    op.create_index(op.f('ix_chantiers_statut'), 'chantiers', ['statut'], unique=False)
    op.create_table('lignes_devis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('devis_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('quantite', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unite', sa.String(), nullable=True),
    sa.Column('prix_unitaire_ht', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['devis_id'], ['devis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lignes_devis_devis_id'), 'lignes_devis', ['devis_id'], unique=False)
    op.create_index(op.f('ix_lignes_devis_id'), 'lignes_devis', ['id'], unique=False)
    op.create_table('chantier_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chantier_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('texte', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chantier_id'], ['chantiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chantier_notes_chantier_id'), 'chantier_notes', ['chantier_id'], unique=False)
    op.create_index(op.f('ix_chantier_notes_id'), 'chantier_notes', ['id'], unique=False)
    op.create_table('depenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chantier_id', sa.Integer(), nullable=False),
    sa.Column('fournisseur_id', sa.Integer(), nullable=True),
    sa.Column('libelle', sa.String(), nullable=False),
    sa.Column('montant', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date_depense', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['chantier_id'], ['chantiers.id'], ),
    sa.ForeignKeyConstraint(['fournisseur_id'], ['fournisseurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_depenses_chantier_id'), 'depenses', ['chantier_id'], unique=False)
    op.create_index(op.f('ix_depenses_fournisseur_id'), 'depenses', ['fournisseur_id'], unique=False)
    op.create_index(op.f('ix_depenses_id'), 'depenses', ['id'], unique=False)
    op.create_table('evenements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artisan_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('chantier_id', sa.Integer(), nullable=True),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('date_debut', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lieu', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisans.id'], ),
    sa.ForeignKeyConstraint(['chantier_id'], ['chantiers.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evenements_artisan_id'), 'evenements', ['artisan_id'], unique=False)
    op.create_index(op.f('ix_evenements_chantier_id'), 'evenements', ['chantier_id'], unique=False)
    op.create_index(op.f('ix_evenements_client_id'), 'evenements', ['client_id'], unique=False)
    op.create_index(op.f('ix_evenements_id'), 'evenements', ['id'], unique=False)
    op.create_table('factures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artisan_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('devis_id', sa.Integer(), nullable=True),
    sa.Column('chantier_id', sa.Integer(), nullable=True),
    sa.Column('contrat_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('taux_tva', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('date_emission', sa.Date(), nullable=True),
    sa.Column('date_echeance', sa.Date(), nullable=True),
    sa.Column('date_envoi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date_derniere_relance', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nb_relances', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisans.id'], ),
    sa.ForeignKeyConstraint(['chantier_id'], ['chantiers.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['contrat_id'], ['contrats.id'], ),
    sa.ForeignKeyConstraint(['devis_id'], ['devis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factures_artisan_id'), 'factures', ['artisan_id'], unique=False)
    op.create_index(op.f('ix_factures_chantier_id'), 'factures', ['chantier_id'], unique=False)
    op.create_index(op.f('ix_factures_client_id'), 'factures', ['client_id'], unique=False)
    op.create_index(op.f('ix_factures_contrat_id'), 'factures', ['contrat_id'], unique=False)
    op.create_index(op.f('ix_factures_devis_id'), 'factures', ['devis_id'], unique=False)
    op.create_index(op.f('ix_factures_id'), 'factures', ['id'], unique=False)
    op.create_index(op.f('ix_factures_statut'), 'factures', ['statut'], unique=False)
    op.create_index(op.f('ix_factures_token'), 'factures', ['token'], unique=True)
    op.create_table('taches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artisan_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('chantier_id', sa.Integer(), nullable=True),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priorite', sa.String(), nullable=True),
    sa.Column('echeance', sa.Date(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisans.id'], ),
    sa.ForeignKeyConstraint(['chantier_id'], ['chantiers.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taches_artisan_id'), 'taches', ['artisan_id'], unique=False)
    op.create_index(op.f('ix_taches_chantier_id'), 'taches', ['chantier_id'], unique=False)
    op.create_index(op.f('ix_taches_client_id'), 'taches', ['client_id'], unique=False)
    op.create_index(op.f('ix_taches_id'), 'taches', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artisan_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('chantier_id', sa.Integer(), nullable=True),
    sa.Column('devis_id', sa.Integer(), nullable=True),
    sa.Column('facture_id', sa.Integer(), nullable=True),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('chemin_fichier', sa.String(), nullable=True),
    sa.Column('nom_original', sa.String(), nullable=True),
    sa.Column('taille_octets', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisans.id'], ),
    sa.ForeignKeyConstraint(['chantier_id'], ['chantiers.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['devis_id'], ['devis.id'], ),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_artisan_id'), 'documents', ['artisan_id'], unique=False)
    op.create_index(op.f('ix_documents_chantier_id'), 'documents', ['chantier_id'], unique=False)
    op.create_index(op.f('ix_documents_client_id'), 'documents', ['client_id'], unique=False)
    op.create_index(op.f('ix_documents_devis_id'), 'documents', ['devis_id'], unique=False)
    op.create_index(op.f('ix_documents_facture_id'), 'documents', ['facture_id'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artisan_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('devis_id', sa.Integer(), nullable=True),
    sa.Column('facture_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('destinataire', sa.String(), nullable=True),
    sa.Column('objet', sa.String(), nullable=True),
    sa.Column('statut', sa.String(), nullable=False),
    sa.Column('erreur', sa.Text(), nullable=True),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisans.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['devis_id'], ['devis.id'], ),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_logs_artisan_id'), 'email_logs', ['artisan_id'], unique=False)
    op.create_index(op.f('ix_email_logs_client_id'), 'email_logs', ['client_id'], unique=False)
    op.create_index(op.f('ix_email_logs_created_at'), 'email_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_logs_devis_id'), 'email_logs', ['devis_id'], unique=False)
    op.create_index(op.f('ix_email_logs_facture_id'), 'email_logs', ['facture_id'], unique=False)
    op.create_index(op.f('ix_email_logs_id'), 'email_logs', ['id'], unique=False)
    op.create_table('lignes_facture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facture_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('quantite', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unite', sa.String(), nullable=True),
    sa.Column('prix_unitaire_ht', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lignes_facture_facture_id'), 'lignes_facture', ['facture_id'], unique=False)
    op.create_index(op.f('ix_lignes_facture_id'), 'lignes_facture', ['id'], unique=False)
    op.create_table('paiements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facture_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date_paiement', sa.Date(), nullable=True),
    sa.Column('moyen', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paiements_facture_id'), 'paiements', ['facture_id'], unique=False)
    op.create_index(op.f('ix_paiements_id'), 'paiements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paiements_id'), table_name='paiements')
    op.drop_index(op.f('ix_paiements_facture_id'), table_name='paiements')
    op.drop_table('paiements')
    op.drop_index(op.f('ix_lignes_facture_id'), table_name='lignes_facture')
    op.drop_index(op.f('ix_lignes_facture_facture_id'), table_name='lignes_facture')
    op.drop_table('lignes_facture')
    op.drop_index(op.f('ix_email_logs_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_facture_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_devis_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_created_at'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_client_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_artisan_id'), table_name='email_logs')
    op.drop_table('email_logs')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_facture_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_devis_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_client_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_chantier_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_artisan_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_taches_id'), table_name='taches')
    op.drop_index(op.f('ix_taches_client_id'), table_name='taches')
    op.drop_index(op.f('ix_taches_chantier_id'), table_name='taches')
    op.drop_index(op.f('ix_taches_artisan_id'), table_name='taches')
    op.drop_table('taches')
    op.drop_index(op.f('ix_factures_token'), table_name='factures')
    op.drop_index(op.f('ix_factures_statut'), table_name='factures')
    op.drop_index(op.f('ix_factures_id'), table_name='factures')
    op.drop_index(op.f('ix_factures_devis_id'), table_name='factures')
    op.drop_index(op.f('ix_factures_contrat_id'), table_name='factures')
    op.drop_index(op.f('ix_factures_client_id'), table_name='factures')
    op.drop_index(op.f('ix_factures_chantier_id'), table_name='factures')
    op.drop_index(op.f('ix_factures_artisan_id'), table_name='factures')
    op.drop_table('factures')
    op.drop_index(op.f('ix_evenements_id'), table_name='evenements')
    op.drop_index(op.f('ix_evenements_client_id'), table_name='evenements')
    op.drop_index(op.f('ix_evenements_chantier_id'), table_name='evenements')
    op.drop_index(op.f('ix_evenements_artisan_id'), table_name='evenements')
    op.drop_table('evenements')
    op.drop_index(op.f('ix_depenses_id'), table_name='depenses')
    op.drop_index(op.f('ix_depenses_fournisseur_id'), table_name='depenses')
    op.drop_index(op.f('ix_depenses_chantier_id'), table_name='depenses')
    op.drop_table('depenses')
    op.drop_index(op.f('ix_chantier_notes_id'), table_name='chantier_notes')
    op.drop_index(op.f('ix_chantier_notes_chantier_id'), table_name='chantier_notes')
    op.drop_table('chantier_notes')
    op.drop_index(op.f('ix_lignes_devis_id'), table_name='lignes_devis')
    op.drop_index(op.f('ix_lignes_devis_devis_id'), table_name='lignes_devis')
    op.drop_table('lignes_devis')
    op.drop_index(op.f('ix_chantiers_statut'), table_name='chantiers')
    op.drop_index(op.f('ix_chantiers_id'), table_name='chantiers')
    op.drop_index(op.f('ix_chantiers_devis_id'), table_name='chantiers')
    op.drop_index(op.f('ix_chantiers_client_id'), table_name='chantiers')
    op.drop_index(op.f('ix_chantiers_artisan_id'), table_name='chantiers')
    op.drop_table('chantiers')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_client_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_artisan_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_devis_token'), table_name='devis')
    op.drop_index(op.f('ix_devis_statut'), table_name='devis')
    op.drop_index(op.f('ix_devis_id'), table_name='devis')
    op.drop_index(op.f('ix_devis_client_id'), table_name='devis')
    op.drop_index(op.f('ix_devis_artisan_id'), table_name='devis')
    op.drop_table('devis')
    op.drop_index(op.f('ix_contrats_id'), table_name='contrats')
    op.drop_index(op.f('ix_contrats_client_id'), table_name='contrats')
    op.drop_index(op.f('ix_contrats_artisan_id'), table_name='contrats')
    op.drop_table('contrats')
    op.drop_index(op.f('ix_avis_id'), table_name='avis')
    op.drop_index(op.f('ix_avis_client_id'), table_name='avis')
    op.drop_index(op.f('ix_avis_artisan_id'), table_name='avis')
    op.drop_table('avis')
    op.drop_index(op.f('ix_prestations_id'), table_name='prestations')
    op.drop_index(op.f('ix_prestations_artisan_id'), table_name='prestations')
    op.drop_table('prestations')
    op.drop_index(op.f('ix_membres_id'), table_name='membres')
    op.drop_index(op.f('ix_membres_email'), table_name='membres')
    op.drop_index(op.f('ix_membres_artisan_id'), table_name='membres')
    op.drop_table('membres')
    op.drop_index(op.f('ix_fournisseurs_id'), table_name='fournisseurs')
    op.drop_index(op.f('ix_fournisseurs_artisan_id'), table_name='fournisseurs')
    op.drop_table('fournisseurs')
    op.drop_index(op.f('ix_conformite_items_id'), table_name='conformite_items')
    op.drop_index(op.f('ix_conformite_items_artisan_id'), table_name='conformite_items')
    op.drop_table('conformite_items')
    op.drop_index(op.f('ix_clients_token_portail'), table_name='clients')
    op.drop_index(op.f('ix_clients_token_avis'), table_name='clients')
    op.drop_index(op.f('ix_clients_statut'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_artisan_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_automation_runs_id'), table_name='automation_runs')
    op.drop_table('automation_runs')
    op.drop_index(op.f('ix_artisans_slug'), table_name='artisans')
    op.drop_index(op.f('ix_artisans_id'), table_name='artisans')
    op.drop_index(op.f('ix_artisans_email'), table_name='artisans')
    op.drop_table('artisans')
    # ### end Alembic commands ###
