"""design profile site vitrine (moteur V2, Lot 1)

Revision ID: c3d4e5f6a7b8
Revises: b5d7e9f1a3c2
Create Date: 2026-08-29 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d4e5f6a7b8'
down_revision: Union[str, None] = 'b5d7e9f1a3c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Nullable et sans server_default volontairement : un site existant
    # garde design_profile=NULL (aucune donnee inventee retroactivement), il
    # recoit un profil proprement a sa prochaine generation (voir
    # app/admin_service.py::ensure_design_profile).
    op.add_column('sites_vitrines', sa.Column('design_profile', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites_vitrines', 'design_profile')
    # ### end Alembic commands ###
